### ISSUE TITLE
[Preprocessing]Read, compare and choose

### ISSUE THREAD

**Issue by yiting-tsai** [mxmgllm/905-toxic_comment_classification#15]
- Read among the papers; 

- Compare different preprocessing to find the most interesting one for our model;

- Preference - using SpaCy, compute syntactics(POS tag).

**Comment by mxmgllm** [comment]
Hello,

I added a template for preprocessing in "src / data /"


This builds software that takes a csv input and returns a new csv.

To complete the software, you define the preprocessor as you want and it will be good.

**Comment by Sophealy** [comment]
Hello,

I will check it out soon. Thank you so much.

Best regards,
Sophea

**Comment by Sophealy** [comment]
I add 2 files to src/data name preprocess1 and preprocess2. 
In preprocess1, I use method from the previous model of the participant in the challenge. 
link: https://github.com/ziyaotang/toxic_comment_classification

In preprocess2, I use method from the model of previous participant in the challenge too. 
link: https://medium.com/@nupurbaghel/toxic-comment-classification-f6e075c3487a

However, I just discover that some the pre-process task they have done may be irrelevant to our purpose. I complied a list of pre-processing task that I think is relevant to the task but I haven't applied it to coding yet. I will do it next week. There are also other pre-processing method from the paper (Is preprocessing of text really worth your time for toxic comment classification?) that I haven't tried too.

**Comment by Sophealy** [comment]
I created a new branch to work on the preprocessing task in case I produced errors or I need to finalized my files before merging to branch master.
