### ISSUE TITLE
[Vizualisation]  Statistical description of variables and distribution plot

### ISSUE THREAD

**Issue by mxmgllm** [mxmgllm/905-toxic_comment_classification#22]

**Comment by yiting-tsai** [comment]
![type of comments](https://user-images.githubusercontent.com/42948497/67088986-d4e2a880-f1a6-11e9-8c64-6f6e3cdd2a80.png)
![distribution of non toxic comments](https://user-images.githubusercontent.com/42948497/67088994-d90ec600-f1a6-11e9-8099-164ea5194ff4.png)
![distribution of toxic comments](https://user-images.githubusercontent.com/42948497/67088997-dad88980-f1a6-11e9-9be4-eb00d33a6e5e.png)
![distribution of severe toxic comments](https://user-images.githubusercontent.com/42948497/67089036-f8a5ee80-f1a6-11e9-8dc7-4c5268a854ce.png)

**Comment by yiting-tsai** [comment]
**TODO:** 
- Correlation metrics
- Verticalize the barplots

**Comment by yiting-tsai** [comment]
Total comment texts in train data: 159571
![Percentage of comments in each class](https://user-images.githubusercontent.com/42948497/67124330-a1c60680-f1f2-11e9-968f-06522eb50348.png)
![Percentage of distribution of types in non toxic comments](https://user-images.githubusercontent.com/42948497/67124347-a68aba80-f1f2-11e9-9683-a00c73fd54cb.png)
![Percentage of distribution of types in toxic comments](https://user-images.githubusercontent.com/42948497/67124354-a985ab00-f1f2-11e9-9024-9c83517eb20f.png)
![Percentage of distribution of types in severe toxic comments](https://user-images.githubusercontent.com/42948497/67124365-abe80500-f1f2-11e9-8f86-418ee468105c.png)
