### ISSUE TITLE
Frequent words in toxic comments.

### ISSUE THREAD

**Issue by mxmgllm** [mxmgllm/905-toxic_comment_classification#40]

**Comment by yiting-tsai** [comment]
![TFIDF_top10_words_per_class](https://user-images.githubusercontent.com/42948497/68343361-e1df2180-00ec-11ea-9cd6-1272b7d5ed7d.png)

**Comment by yiting-tsai** [comment]
TFIDF top 20 words per class
![TFIDF_top20_words_per_class](https://user-images.githubusercontent.com/42948497/68343797-e952fa80-00ed-11ea-80b0-9fae4663c656.png)

**Comment by yiting-tsai** [comment]
![Toxic_top20_list](https://user-images.githubusercontent.com/42948497/68345099-db52a900-00f0-11ea-801c-10aa3f603f19.png)
![severe_toxic_top20_list](https://user-images.githubusercontent.com/42948497/68345106-de4d9980-00f0-11ea-931b-b55653dcdb0e.png)
![Obscene_top20_list](https://user-images.githubusercontent.com/42948497/68345113-e0aff380-00f0-11ea-9cde-85c724db85c5.png)
![Threat_top20_list](https://user-images.githubusercontent.com/42948497/68345122-e7d70180-00f0-11ea-931c-d9d2dd82df31.png)
![Insult_top20_list](https://user-images.githubusercontent.com/42948497/68345124-e9a0c500-00f0-11ea-8a69-0df4d6369a4f.png)
![identity_hate_top20_list](https://user-images.githubusercontent.com/42948497/68345129-eb6a8880-00f0-11ea-882b-eff0bc29cb5d.png)
